export default [
  {
    id: 1,
    category: "food",
    picture: "/images/Frame1.png",
    title: "Taco Truck Meetup",
    host: "Ava Nguyen",
    date: "14/02-2025",
    attendents: 22,
    saved: true,
  },
  {
    id: 2,
    category: "music",
    picture: "/images/Frame2.png",
    title: "Riverside Jazz Night",
    host: "Liam Carter",
    date: "28/03-2025",
    attendents: 75,
    saved: false,
  },
  {
    id: 3,
    category: "tech",
    picture: "/images/Frame3.png",
    title: "Hack Night: Build & Pizza",
    host: "Priya Shah",
    date: "09/04-2025",
    attendents: 48,
    saved: true,
  },
  {
    id: 4,
    category: "sports",
    picture: "/images/Frame4.png",
    title: "Community 5K Fun Run",
    host: "Marcus Lee",
    date: "21/05-2025",
    attendents: 130,
    saved: false,
  },
  {
    id: 5,
    category: "arts",
    picture: "/images/Frame1.png",
    title: "Paint & Sip Evening",
    host: "Elena Rossi",
    date: "12/06-2025",
    attendents: 32,
    saved: false,
  },
  {
    id: 6,
    category: "outdoor",
    picture: "/images/Frame2.png",
    title: "Sunset Hike at Ridge Trail",
    host: "Jonas Müller",
    date: "03/07-2025",
    attendents: 18,
    saved: true,
  },
  {
    id: 7,
    category: "indoor",
    picture: "/images/Frame3.png",
    title: "Board Game Night",
    host: "Sara Kim",
    date: "25/08-2025",
    attendents: 26,
    saved: false,
  },
  {
    id: 8,
    category: "community",
    picture: "/images/Frame4.png",
    title: "Park Cleanup & Coffee",
    host: "Diego Alvarez",
    date: "07/09-2025",
    attendents: 54,
    saved: true,
  },
];
