export default [
  {
    id: 1,
    category: "outdoor",
    picture: "/hidethepain.jpg",
    title: "Walk in the park",
    host: "Niklas",
    data: "03/12-2025",
    attendents: 40,
    saved: false,
  },
  {
    id: 2,
    category: "outdoor",
    picture: "/hidethepain.jpg",
    title: "Walk in the park",
    host: "Niklas",
    data: "03/12-2025",
    attendents: 40,
    saved: false,
  },
  {
    id: 3,
    category: "outdoor",
    picture: "/hidethepain.jpg",
    title: "Walk in the park",
    host: "Niklas",
    data: "03/12-2025",
    attendents: 40,
    saved: false,
  },
  {
    id: 4,
    category: "outdoor",
    picture: "/hidethepain.jpg",
    title: "Walk in the park",
    host: "Niklas",
    data: "03/12-2025",
    attendents: 40,
    saved: false,
  },
  {
    id: 5,
    category: "outdoor",
    picture: "/hidethepain.jpg",
    title: "Walk in the park",
    host: "Niklas",
    data: "03/12-2025",
    attendents: 40,
    saved: false,
  },
  {
    id: 6,
    category: "outdoor",
    picture: "/hidethepain.jpg",
    title: "Walk in the park",
    host: "Niklas",
    data: "03/12-2025",
    attendents: 40,
    saved: false,
  },
  {
    id: 7,
    category: "outdoor",
    picture: "/hidethepain.jpg",
    title: "Walk in the park",
    host: "Niklas",
    data: "03/12-2025",
    attendents: 40,
    saved: false,
  },
  {
    id: 8,
    category: "outdoor",
    picture: "/hidethepain.jpg",
    title: "Walk in the park",
    host: "Niklas",
    data: "03/12-2025",
    attendents: 40,
    saved: false,
  },
];
